### GLASS IDENTIFICATION PROJECT

In [1]:
import pandas as pd
import  numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [2]:
df=pd.read_csv('https://raw.githubusercontent.com/FlipRoboTechnologies/ML-Datasets/main/Glass%20Identification/Glass%20Identification.csv')
df

       1  1.52101  13.64  4.49  1.10  71.78  0.06  8.75  0.00  0.00.1  1.1
0      2  1.51761  13.89  3.60  1.36  72.73  0.48  7.83  0.00    0.00    1
1      3  1.51618  13.53  3.55  1.54  72.99  0.39  7.78  0.00    0.00    1
2      4  1.51766  13.21  3.69  1.29  72.61  0.57  8.22  0.00    0.00    1
3      5  1.51742  13.27  3.62  1.24  73.08  0.55  8.07  0.00    0.00    1
4      6  1.51596  12.79  3.61  1.62  72.97  0.64  8.07  0.00    0.26    1
..   ...      ...    ...   ...   ...    ...   ...   ...   ...     ...  ...
208  210  1.51623  14.14  0.00  2.88  72.61  0.08  9.18  1.06    0.00    7
209  211  1.51685  14.92  0.00  1.99  73.06  0.00  8.40  1.59    0.00    7
210  212  1.52065  14.36  0.00  2.02  73.42  0.00  8.44  1.64    0.00    7
211  213  1.51651  14.38  0.00  1.94  73.61  0.00  8.48  1.57    0.00    7
212  214  1.51711  14.23  0.00  2.08  73.36  0.00  8.62  1.67    0.00    7

[213 rows x 11 columns]

In [3]:
df.head(15)

     1  1.52101  13.64  4.49  1.10  71.78  0.06  8.75  0.00  0.00.1  1.1
0    2  1.51761  13.89  3.60  1.36  72.73  0.48  7.83   0.0    0.00    1
1    3  1.51618  13.53  3.55  1.54  72.99  0.39  7.78   0.0    0.00    1
2    4  1.51766  13.21  3.69  1.29  72.61  0.57  8.22   0.0    0.00    1
3    5  1.51742  13.27  3.62  1.24  73.08  0.55  8.07   0.0    0.00    1
4    6  1.51596  12.79  3.61  1.62  72.97  0.64  8.07   0.0    0.26    1
5    7  1.51743  13.30  3.60  1.14  73.09  0.58  8.17   0.0    0.00    1
6    8  1.51756  13.15  3.61  1.05  73.24  0.57  8.24   0.0    0.00    1
7    9  1.51918  14.04  3.58  1.37  72.08  0.56  8.30   0.0    0.00    1
8   10  1.51755  13.00  3.60  1.36  72.99  0.57  8.40   0.0    0.11    1
9   11  1.51571  12.72  3.46  1.56  73.20  0.67  8.09   0.0    0.24    1
10  12  1.51763  12.80  3.66  1.27  73.01  0.60  8.56   0.0    0.00    1
11  13  1.51589  12.88  3.43  1.40  73.28  0.69  8.05   0.0    0.24    1
12  14  1.51748  12.86  3.56  1.27  73.21  0.54  8.38   0.0    0.17    1
13  15  1.51763  12.61  3.59  1.31  73.29  0.58  8.50   0.0    0.00    1
14  16  1.51761  12.81  3.54  1.23  73.24  0.58  8.39   0.0    0.00    1

In [4]:
df.tail(30)

       1  1.52101  13.64  4.49  1.10  71.78  0.06  8.75  0.00  0.00.1  1.1
183  185  1.51115  17.38  0.00  0.34  75.41  0.00  6.65  0.00    0.00    6
184  186  1.51131  13.69  3.20  1.81  72.81  1.76  5.43  1.19    0.00    7
185  187  1.51838  14.32  3.26  2.22  71.25  1.46  5.79  1.63    0.00    7
186  188  1.52315  13.44  3.34  1.23  72.38  0.60  8.83  0.00    0.00    7
187  189  1.52247  14.86  2.20  2.06  70.26  0.76  9.76  0.00    0.00    7
188  190  1.52365  15.79  1.83  1.31  70.43  0.31  8.61  1.68    0.00    7
189  191  1.51613  13.88  1.78  1.79  73.10  0.00  8.67  0.76    0.00    7
190  192  1.51602  14.85  0.00  2.38  73.28  0.00  8.76  0.64    0.09    7
191  193  1.51623  14.20  0.00  2.79  73.46  0.04  9.04  0.40    0.09    7
192  194  1.51719  14.75  0.00  2.00  73.02  0.00  8.53  1.59    0.08    7
193  195  1.51683  14.56  0.00  1.98  73.29  0.00  8.52  1.57    0.07    7
194  196  1.51545  14.14  0.00  2.68  73.39  0.08  9.07  0.61    0.05    7
195  197  1.51556  13.87  0.00  2.54  73.23  0.14  9.41  0.81    0.01    7
196  198  1.51727  14.70  0.00  2.34  73.28  0.00  8.95  0.66    0.00    7
197  199  1.51531  14.38  0.00  2.66  73.10  0.04  9.08  0.64    0.00    7
198  200  1.51609  15.01  0.00  2.51  73.05  0.05  8.83  0.53    0.00    7
199  201  1.51508  15.15  0.00  2.25  73.50  0.00  8.34  0.63    0.00    7
200  202  1.51653  11.95  0.00  1.19  75.18  2.70  8.93  0.00    0.00    7
201  203  1.51514  14.85  0.00  2.42  73.72  0.00  8.39  0.56    0.00    7
202  204  1.51658  14.80  0.00  1.99  73.11  0.00  8.28  1.71    0.00    7
203  205  1.51617  14.95  0.00  2.27  73.30  0.00  8.71  0.67    0.00    7
204  206  1.51732  14.95  0.00  1.80  72.99  0.00  8.61  1.55    0.00    7
205  207  1.51645  14.94  0.00  1.87  73.11  0.00  8.67  1.38    0.00    7
206  208  1.51831  14.39  0.00  1.82  72.86  1.41  6.47  2.88    0.00    7
207  209  1.51640  14.37  0.00  2.74  72.85  0.00  9.45  0.54    0.00    7
208  210  1.51623  14.14  0.00  2.88  72.61  0.08  9.18  1.06    0.00    7
209  211  1.51685  14.92  0.00  1.99  73.06  0.00  8.40  1.59    0.00    7
210  212  1.52065  14.36  0.00  2.02  73.42  0.00  8.44  1.64    0.00    7
211  213  1.51651  14.38  0.00  1.94  73.61  0.00  8.48  1.57    0.00    7
212  214  1.51711  14.23  0.00  2.08  73.36  0.00  8.62  1.67    0.00    7

In [5]:
df.shape

(213, 11)

In [6]:
df.columns

Index(['1', '1.52101', '13.64', '4.49', '1.10', '71.78', '0.06', '8.75',
       '0.00', '0.00.1', '1.1'],
      dtype='object')